DROP DATABASE IF EXISTS librarybot;
CREATE DATABASE librarybot;

USE librarybot;

CREATE TABLE user (
	userid VARCHAR(256) NOT NULL PRIMARY KEY
);

CREATE TABLE books (
	bookid INT(15) NOT NULL AUTO_INCREMENT,
	title VARCHAR(256) NOT NULL,
	author VARCHAR(256) NOT NULL,
	category VARCHAR(256) NOT NULL,
	borrower VARCHAR(256) DEFAULT NULL
);
