DROP DATABASE IF EXISTS librarybot;
CREATE DATABASE librarybot;

USE librarybot;

CREATE TABLE user (
	userid VARCHAR(256) NOT NULL PRIMARY KEY
);

CREATE TABLE books (
	bookid INT(15) NOT NULL AUTO_INCREMENT,
	title TEXT NOT NULL,
	author TEXT NOT NULL,
	category TEXT NOT NULL,
	borrower VARCHAR(256) DEFAULT NULL,
	PRIMARY KEY (bookid)
);
