USE librarybot;
INSERT INTO books(title,author,category) values ("Gifted Hands, Kids Edition: The Ben Carson Story (ZonderKidz Biography)","Gregg Lewis","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("David and the Giant (I Can Read! / The Beginner's Bible)","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Adventure Bible Book of Devotions, NIV: 365 Days of Adventure","Robin Schmitt","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Berenstain Bears Blessed are the Peacemakers (Berenstain Bears/Living Lights)","Mike Berenstain","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Jesus Saves the World (I Can Read! / The Beginner's Bible)","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Big Book of Homeschooling","Debi Pearl","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Submarines, Secrets and a Daring Rescue (American Revolutionary War Adventures)","Robert J. Skead","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Berenstain Bears Keep the Faith (Berenstain Bears/Living Lights)","Mike Berenstain","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Big Book of Bible Skills: Ages 8E€E12; reproducible, B/W, group activities, games, puzzles, activities that help kids learn to use their Bibles, learn Bible books, more (Big Books)","Gospel Light","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Noah and the Ark (I Can Read! / The Beginner's Bible)","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The World of Animals (God's Design for Life)","Debbie Lawrence","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Case for Catholic Education: Why Parents, Teachers, and Politicians Should Reclaim the Principles of Catholic Pedagogy","Ryan N.S. Topping","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Streams in the Desert for Kids: 365 Devotions of God's Awesome Love","L. B. E. Cowman","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Horizons Mathematics K, Book 1 (Lifepac)","Kindergarten","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Genesis: Finding Our Roots","Ruth Beechick","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Gladys Aylward: The Adventure of a Lifetime (Christian Heroes: Then & Now)","Janet Benge","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Jesus and His Friends / JesÃºs y sus amigos (I Can Read! / The Beginner's Bible / Â¡Yo sÃ© leer!)","Zondervan","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Psalm 23","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Ultimate Guide to Homeschooling Teens","Debra Bell","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Successful Homeschool Family Handbook","Dorothy Moore","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Clash: A Novel (Soul Surfer Series)","Rick Bundschuh","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Bob and Larry in the Case of the Missing Patience (I Can Read! / Big Idea Books / VeggieTales)","Karen Poth","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Beautiful Girlhood: Revised by Karen Andreola","Karen Andreola","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Jesus Saves the World / JesÃºs salva al mundo (I Can Read! / The Beginner's Bible / Â¡Yo sÃ© leer!)","Zondervan","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Baby Moses and the Princess (I Can Read! / The Beginner's Bible)","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Berenstain Bears: God Bless Our Home (Berenstain Bears/Living Lights)","Jan Berenstain","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Every Which Way to Pray (Everyday Zoo)","Joyce Meyer","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Beginner's Bible Kid-Sized Devotions","Zondervan","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Miracles of Jesus (I Can Read! / Adventure Bible)","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Berenstain Bears and the Easter Story (Berenstain Bears/Living Lights)","Mike Berenstain","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Story Trading Cards: For Preschool: Pre-K through Grade 2","Zondervan","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Seasons of a Mother's Heart, 2nd edition","Sally Clarkson","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Favorite Parables from the Bible: Stories Jesus Told","Nick Butterworth","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Horizons Mathematics 1: Book Two (Lifepac)","Sareta A. Cummins","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Moses, God's Brave Servant: Biblical Values (I Can Read! / Dennis Jones Series)","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Berenstain Bears  and the Trouble with Things (Berenstain Bears/Living Lights)","Jan & Mike Berenstain","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Wisdom and Eloquence: A Christian Paradigm for Classical Learning","Robert Littlejohn","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Jonah and the Big Fish / JonÃ¡s y el gran pez (I Can Read! / The Beginner's Bible / Â¡Yo sÃ© leer!)","Zondervan","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Cold-Case Christianity: A Homicide Detective Investigates the Claims of the Gospels","J. Warner Wallace","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Valley of Vision: A Collection of Puritan Prayers & Devotions","","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Jesus and the Disinherited","Howard Thurman","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Crucifixion: Understanding the Death of Jesus Christ","Fleming Rutledge","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("A Concise History of Christian Thought","Tony Lane","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("Christ Actually: Reimagining Faith in the Modern Age","James Carroll","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("A Light in Darkness Vol. 1: Seven Messages To The Seven Churches","Rick Renner","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Misunderstood Jew: The Church and the Scandal of the Jewish Jesus","Amy-Jill Levine","Christian Books & Bibles");
INSERT INTO books(title,author,category) values ("The Asthma Sourcebook 3rd Edition (Sourcebooks)","Francis Adams","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("The Bible Cure for Asthma: Ancient Truths, Natural Remedies and the Latest Findings for Your Health Today (New Bible Cure (Siloam))","Don Colbert MD","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Allergies and Asthma For Dummies","William E. Berger","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("The Harvard Medical School Guide to Taking Control of Asthma (The Harvard Medical School Guides)","Christopher H. Fanta","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Courage and Information for Life with Chronic Obstructive Pulmonary Disease: The Handbook for Patients, Families and Care Givers Managing COPD, Emphysema, Bronchitis","Rick Carter","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Natural Relief from Asthma (Natural Health Guide)","C. Leigh Broadhurst","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Dr. Dean Mitchell's Allergy and Asthma Solution: The Ultimate Program for Reversing Your Symptoms One Drop at a Time","M.D. Dean Mitchell M.D.","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Yoga Beats Asthma: Simple Exercises and Breathing Techniques to Relieve Asthma and Other Respiratory Disorders","Stella Weller","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Live Free from Asthma and Allergies: Use the BioSET System to Detoxify and Desensitize Your Body","Ellen W. Cutler","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Golden Wings, Holistic Approach to Managing Asthma","Yocheved Bat-Imedt R.N.","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("In Sickness and in Play: Children Coping with Chronic Illness (Series in Childhood Studies)","Cindy Dell Clark","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("The Washington ManualÂ® Allergy, Asthma, and Immunology Subspecialty Consult (The Washington ManualÂ® Subspecialty Consult Series)","Washington University School of Medicine Department of Medicine","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Asthma Free in 21 Days: The Breakthrough Mind-Body Healing Program","Kathryn Shafer","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("BREATHLESS  CL","Louise A. DeSalvo","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("The Harvard Medical School Guide To Taking Control Of Asthma","Lynda, M.D. Cristiano","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Immunotherapy in Asthma (Lung Biology in Health and Disease)","","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Dr Tom Plaut's Asthma Guide for People of All Ages","Thomas F. Plaut","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Gastroesophageal Reflux Disease and Airway Disease (Lung Biology in Health and Disease)","","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Endogenous Respiration","Vladimir Frolov","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("All About Asthma: Stop Suffering And Start Living","Irwin J. Polk","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Winning the War Against Asthma and Allergies","Ellen W. Cutler","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Asthma and COPD: Basic Mechanisms and Clinical Management","Peter J. Barnes DM FRS FMedSci","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("One Minute Asthma: What You Need to Know","Thomas F. Plaut","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Severe Asthma: Pathogenesis and Clinical Management (Lung Biology in Health and Disease)","","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("El asma en un minuto: Lo que usted necesita saber (Spanish Edition)","Thomas F. Plaut","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("One Minute Asthma: What You Need to Know","Thomas F. Plaut","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Environmental Asthma (Lung Biology in Health and Disease)","Robert K. Bush","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Freedom from Asthma: The Revolutionary 5-Day Treatment for Healing  Asthma with the Breath Connection (R) Program","alexander Alexander Stalmatski","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("All about Asthma (An Albert Whitman Prairie Book)","Vivianne Astrow","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("IgE and Anti-IgE Therapy in Asthma and Allergic Disease (Lung Biology in Health and Disease)","","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Natural Asthma & Allergy Management","Celeste White","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Intrinsic Asthma (Agents and Actions Supplements)","M. Schmitz-Schumann","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Living with Asthma: A Comprehensive Guide to Understanding and Controlling Asthma...","Anthony Rooklin","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Asthma: An Alternative Approach","Ron Roberts","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Asthma & Exercise","Nancy Hogshead","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("The Asthma Self-Help Book, Revised 2nd Edition: How to Live a Normal Life in Spite of Your Condition","Paul J. Hannaway","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("The Whole Family Guide to Natural Asthma Relief: comph Drug Free solns for Treatment Prevention Asthma Allergies","Ph.D C. Leigh Broadhurst","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Asthma","Peter J. Barnes","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Airway Remodeling (Lung Biology in Health and Disease)","","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Allergy and Asthma Relief","William Berger","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Asthma: Epidemiology, Anti-Inflammatory Therapy and Future Trends (Respiratory Pharmacology and Pharmacotherapy)","","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("The Asthma Breakthrough: Breathe Freely-Naturally!","Henry Osiecki","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Asthma","Allan M. Weinstein","Health, Fitness & Dieting");
INSERT INTO books(title,author,category) values ("Harry Potter And The Chamber Of Secrets","J. K. Rowling","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Illuminae (The Illuminae Files)","Amie Kaufman","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Eleanor & Park","Rainbow Rowell","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Queen of Shadows (Throne of Glass)","Sarah J. Maas","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The 5th Wave: The First Book of the 5th Wave Series","Rick Yancey","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Hollow City: The Second Novel of Miss Peregrine's Peculiar Children","Ransom Riggs","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Waterfire Saga, Book Three Dark Tide","Jennifer Donnelly","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Boy's Body Book: Third Edition: Everything You Need to Know for Growing Up YOU","Kelli Dunham","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Harry Potter and the Prisoner of Azkaban","J.K. Rowling","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Divergent Series Ultimate Four-Book Box Set: Divergent, Insurgent, Allegiant, Four","Veronica Roth","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Judy Blume's Fudge Box Set","Judy Blume","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Harry Potter and the Deathly Hallows (Book 7)","J. K. Rowling","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Heir (The Selection)","Kiera Cass","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Red Queen","Victoria Aveyard","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Fault in Our Stars","John Green","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Thirteen Reasons Why","Jay Asher","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Allegiant (Divergent Series)","Veronica Roth","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Boy in the Striped Pajamas (Young Reader's Choice Award - Intermediate Division)","John Boyne","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Rest of Us Just Live Here","Patrick Ness","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Game of Lives (The Mortality Doctrine, Book Three)","James Dashner","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Nimona","Noelle Stevenson","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("A Smart Girl's Guide: Drama, Rumors & Secrets: Staying True to Yourself in Changing Times (Smart Girl's Guides)","Nancy Holyoke","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Giver Quartet boxed set","Lois Lowry","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Infinite Sea: The Second Book of the 5th Wave","Rick Yancey","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Fangirl: A Novel","Rainbow Rowell","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Everything, Everything","Nicola Yoon","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Breakaway: Beyond the Goal","Alex Morgan","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Divergent (Divergent Series)","Veronica Roth","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Rookie Yearbook Four","Tavi Gevinson","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Cinder: Book One of the Lunar Chronicles","Marissa Meyer","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Insurgent (Divergent Series)","Veronica Roth","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("We Were Liars","E. Lockhart","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Symphony for the City of the Dead: Dmitri Shostakovich and the Siege of Leningrad","M.T. Anderson","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Color Me Creative: Unlock Your Imagination","Kristina Webb","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Elements of Harmony: Friendship is Magic (My Little Pony)","Brandon T. Snider","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Taking Flight: From War Orphan to Star Ballerina","Michaela DePrince","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("All I Know Now: Wonderings and Advice on Making Friends, Making Mistakes, Falling in (and out of) Love, and Other Adventures in Growing Up Hopefully","Carrie Hope Fletcher","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Book of Virtues for Young People: A Treasury of Great Moral Stories","","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Twilight Saga: The Complete Film Archive: Memories, Mementos, and Other Treasures from the Creative Team Behind the Beloved Motion Pictures","Robert Abele","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("The Fashion Coloring Book","Carol Chu","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Ah-Ha to Zig-Zag: 31 Objects from Cooper Hewitt, Smithsonian Design Museum","Maira Kalman","Teen & Young Adult");
INSERT INTO books(title,author,category) values ("Acting for Young Actors: The Ultimate Teen Guide","Mary Lou Belli","Teen & Young Adult");
